FROM ghcr.io/waylonwalker/markata-go-builder:sha-90c0778

ENV TZ="America/Chicago"

WORKDIR /site
COPY . /site

EXPOSE 8000
CMD ["markata-go", "serve", "--host", "0.0.0.0", "--port", "8000", "--fast"]
